---
- hosts: localhost
  tasks:
    - name: echo '{{processing_step}}'
      command: echo "{{processing_step}}"

    - name: Kleiner gleich 5
      debug:
        msg: "kleiner gleich"
      when: processing_step|int <= 5

    - name: Grösser als 5
      debug:
        msg: "grösser als"
      when: processing_step|int > 5

    - name: handling
      command: echo "har"

    - name: taa
      include_tasks: setup.yml


