---
- name: set processing file
  vars:
    processing_step: 1
  template:
    src: ../templates/processing_step.txt.tpl
    dest: '{{ processing_step_file }}'
    mode: '0660'
    force: no

# First step =================================
- name: first step
  debug:
    msg: "Step 1"
  when: lookup('file', processing_step_file)|int <= 1

- name: create dest folder
  file: 
    path: /home/{{ ansible_ssh_user }}/data/input
    state: directory
    mode: '0700'
  when: lookup('file', processing_step_file)|int <= 1

  #- name: unzip files
  #  shell: |
  #    for i in /home/ubuntu/data/subset_buildings/*.tar;
  #      do echo extracting ${i};tar -xzvf ${i} -C /home/ubuntu/data/input/;
  #    done
  #  when: lookup('file', processing_step_file)|int <= 1


- name: first step accomplished
  vars:
    processing_step: 2
  template:
    src: ../templates/processing_step.txt.tpl
    dest: '{{ processing_step_file }}'
    mode: '0660'
    force: yes
  when: lookup('file', processing_step_file)|int <= 1

# Second step =================================
- name: Second step
  debug:
    msg: "Step 2"
  when: lookup('file', processing_step_file)|int == 2

