---
- name: create dir
  file: 
    path: /home/{{ ansible_ssh_user }}/.aws
    state: directory
    mode: '0700'

- name: symbolic link 
  file:
    src: /home/{{ ansible_ssh_user }}/data/admin/test.txt
    dest: /home/{{ ansible_ssh_user }}/.aws/credentials
    owner: '{{ ansible_ssh_user }}'
    state: link
    mode: '400'

- name: symbolic links config
  file:
    src: /home/{{ ansible_ssh_user }}/data/admin/test2.txt
    dest: /home/{{ ansible_ssh_user }}/.aws/config
    owner: '{{ ansible_ssh_user }}'
    state: link
    mode: '400'
