---
- name: create dir
  file: 
    path: /home/{{ my_user }}/.aws
    owner: '{{ my_user }}'
    state: directory
    mode: '0700'

- name: symbolic link 
  file:
    src: /home/{{ my_user }}/data/admin/test.txt
    dest: /home/{{ my_user }}/.aws/credentials
    owner: '{{ my_user }}'
    state: link
    mode: '440'

- name: symbolic links config
  file:
    src: /home/{{ my_user }}/data/admin/test2.txt
    dest: /home/{{ my_user }}/.aws/config
    owner: '{{ my_user }}'
    state: link
    mode: '440'

- name: create dir
  file: 
    path: /home/{{ ansible_ssh_user }}/.aws
    owner: '{{ ansible_ssh_user }}'
    state: directory
    mode: '0700'

- name: symbolic link 
  file:
    src: /home/{{ my_user }}/data/admin/test.txt
    dest: /home/{{ ansible_ssh_user }}/.aws/credentials
    owner: '{{ ansible_ssh_user }}'
    state: link
    mode: '440'

- name: symbolic links config
  file:
    src: /home/{{ my_user }}/data/admin/test2.txt
    dest: /home/{{ ansible_ssh_user }}/.aws/config
    owner: '{{ ansible_ssh_user }}'
    state: link
    mode: '440'
